app/controllers/application_controller.rb
app/controllers/favorite_controller.rb
app/controllers/pets_controller.rb
app/controllers/reviews_controller.rb
app/models/favorite.rb
app/views/layouts/application.html.erb
app/views/pets/index.html.erb
config/routes.rb
spec/features/favorites/favorites_indicator_spec.rb
spec/features/favorites/no_favorites_on_index_shows_text_spec.rb
spec/features/favorites/only_favorite_a_pet_once_spec.rb
spec/features/favorites/remove_all_favorites_at_once_spec.rb
spec/features/favorites/remove_favorite_from_favorites_page_spec.rb
spec/features/pets/new_spec.rb

Writing specs for future stories

Add tests 12 thru 15

---

spec/features/applications/new_application_spec.rb

Co-Authored-By: adumortier <adumortier@users.noreply.github.com>

Add spec for pet applications story 16

---

app/controllers/applications_controller.rb
app/models/application.rb
app/models/application_pet.rb
app/models/favorite.rb
app/models/pet.rb
app/views/applications/new.html.erb
app/views/favorites/index.html.erb
config/routes.rb
db/migrate/20200208171707_create_applications.rb
db/migrate/20200208172038_create_application_pets.rb
db/schema.rb
spec/features/applications/new_application_spec.rb
spec/models/application_pets_spec.rb
spec/models/application_spec.rb
spec/models/favorite_spec.rb
spec/models/pets_spec.rb

User story 16

---

app/controllers/applications_controller.rb
spec/features/applications/new_application_spec.rb

User story 17

---

app/controllers/applications_controller.rb
app/controllers/favorites_controller.rb
app/views/applications/show.html.erb
app/views/favorites/index.html.erb
config/routes.rb
spec/features/applications/new_application_spec.rb
spec/features/applications/show_application_spec.rb

Completed user stories 18 and 19

User story 18-19

---

app/controllers/application_pets_controller.rb
app/views/application_pets/index.html.erb
app/views/applications/show.html.erb
app/views/pets/show.html.erb
config/routes.rb
spec/features/application_pets/application_pets_index_spec.rb

User story 20

---

app/views/application_pets/index.html.erb
spec/features/application_pets/no_applications_on_index_spec.rb

Story 21 round 2

---

app/controllers/application_pets_controller.rb
app/views/applications/show.html.erb
app/views/pets/show.html.erb
config/routes.rb
db/migrate/20200209170655_change_adopted_to_be_string_in_pets.rb
db/schema.rb
spec/features/application_pets/application_pets_index_spec.rb
spec/features/applications/application_approval_spec.rb
spec/features/pets/show_spec.rb

User story 22

---

app/controllers/application_pets_controller.rb
app/views/applications/show.html.erb
config/routes.rb
spec/features/applications/multiple_applications_approval_spec.rb

User story 23

---

app/views/applications/show.html.erb
spec/features/applications/only_one_application_approved_per_pet_spec.rb

User story 24

---

app/controllers/application_pets_controller.rb
app/views/applications/show.html.erb
spec/features/applications/multiple_applications_approval_spec.rb
spec/features/applications/revoke_application_spec.rb

User story 25

---

app/controllers/shelters_controller.rb
app/models/shelter.rb
spec/features/shelters/edit_spec.rb
spec/features/shelters/new_spec.rb
spec/models/shelters_spec.rb

User story 29

---

app/models/pet.rb
app/models/shelter.rb
spec/features/applications/revoke_application_spec.rb
spec/features/shelters/show_spec.rb
spec/models/shelters_spec.rb

User story 30 part2

---

app/controllers/pets_controller.rb
spec/features/pets/delete_spec.rb

User story 32

---

app/views/applications/new.html.erb
app/views/shelter_pets/index.html.erb
spec/features/pets/delete_spec.rb

Name links check

---

app/views/reviews/edit.html.erb
app/views/reviews/new.html.erb
spec/features/reviews/edit_spec.rb
spec/features/reviews/new_spec.rb

Added rating drop down to the `new` and `edit` pages for the `reviews`

Rating drop down

---

db/seeds.rb
spec/features/pets/delete_spec.rb

Fix issues by adding destroy alls before specs

Edit branch

---

app/controllers/pets_controller.rb

Added a check for the `age` attribute of `pet`

Positive age check

---

app/models/shelter.rb
app/views/pets/_form.html.erb
app/views/pets/edit.html.erb
app/views/pets/new.html.erb

Add more partials and try to implement more that still do not accept the pre populated drop down menus

More partials

---

app/controllers/application_controller.rb
app/controllers/application_pets_controller.rb
app/controllers/applications_controller.rb
app/controllers/reviews_controller.rb
app/views/layouts/application.html.erb
app/views/pets/_form.html.erb
app/views/pets/show.html.erb
spec/features/application_pets/application_pets_index_spec.rb
spec/features/applications/application_approval_spec.rb
spec/features/applications/multiple_applications_approval_spec.rb
spec/features/applications/new_application_spec.rb
spec/features/applications/only_one_application_approved_per_pet_spec.rb
spec/features/applications/revoke_application_spec.rb
spec/features/applications/show_application_spec.rb
spec/features/favorites/only_favorite_a_pet_once_spec.rb
spec/features/pets/edit_spec.rb
spec/features/reviews/edit_spec.rb
spec/features/reviews/new_spec.rb
spec/features/shelters/cannot_delete_with_approved_pets_spec.rb
spec/features/shelters/show_spec.rb
spec/models/application_pets_spec.rb
spec/models/application_spec.rb
spec/models/favorite_spec.rb
spec/models/review_spec.rb
spec/models/shelters_spec.rb

Co-Authored-By: adumortier <adumortier@users.noreply.github.com>

Minor edits with spacing to improve looks
